<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User-Defined Functions</title>
</head>
<body>

    <?php

        // Create a function
        function sayHello() {
            echo "Hello";
        }

        // Call function
        sayHello();

        echo "<br>";

        // Returning data generated by the function
        function myName() {
            return "Gabriel";
        }

        $result = myName();
        echo $result;

        echo "<br>";

        // ---------- Parameters ----------

        // You can also set a default value like = "dog" if the parameter is empty
        function yourPet($pet = "dog", $food = "meat") {
            return "Your pet is a " . $pet . " and he likes to eat " . $food . ".";
        }

        // The value Cat was passed to $name to be used inside of the function
        $myPet = yourPet("cat", "fish and chips");
        echo $myPet;

        echo "<br>";

        // --------- Calculator ----------

        function calculator(int $num1, int $num2) {
            $result = $num1 + $num2;
            return $result;
        }

        $total = calculator(10, 20);
        echo $total;

    ?>
    
</body>
</html>